name: k8s containerd test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install apt-get packages
      run: |
        sudo ACCEPT_EULA=Y apt-get update
        sudo ACCEPT_EULA=Y apt-get upgrade
        sudo ACCEPT_EULA=Y apt-get install git wget

    - name: Install containerd and crun
      run: |
        bash containerd/install.sh

    - name: Installing and starting k8s
      run: |
        bash kubernetes_containerd/install.sh > k8s.log 2>&1

    - name: Sleep for 1200s
      run: sleep 1200s
      shell: bash

    - name: Run WasmEdge in k8s
      run: |
        cat k8s.log
        bash kubernetes_containerd/simple_wasi_application.sh
